### ISSUE TITLE
Content Suggestion: Bitcoin & Co. Podcast

### ISSUE THREAD

**Issue by anitaposch** [bitcoin-only/bitcoin-only#107]
1) Link to Content: https://bitcoinundco.com/en/
2) Briefly Describe Content: 
The Philosophy, Ideas and People Behind Bitcoin. With Anita Posch
3) Suggested Section: Podcasts

Thank you!
Anita

**Comment by 6102bitcoin** [comment]
Thank you for the heads up - **Sorry it has taken this long to review your recommendation.**

The podcast is very well made and I am enjoying listening to it currently.

Unfortunately the podcast sponsor CardWallet makes impossible claims about security ("the private key is sealed tamper-proof before the card leaves the production machine, and **immediately deleted after the process** so that not even the staff at the high-security room can ever see the key. High-quality security materials and tamper-proof features prevent a manipulation of the card.")

Because of this I am unable to list your podcast. Would it be possible for you to add a note on the security trade-off that is being made in the podcast when you mention this sponsor?

If this is not possible I understand but hopefully you can understand why I can not list. 

Thanks,
6102

**Comment by anitaposch** [comment]
Hi, thanks for your message. I completely understand your concerns. The manufacturer themselves know about the trade-offs. And it is just for complete noobs, who do not know how to use a hardware wallet.  I changed the text, is this sufficient as a note in your opinion?

not your keys, not your coins - the industry standard is to use a hardware wallet, but if - for various reasons - you cannot use a hardware wallet to secure your bitcoin, then the Card Wallet is the solution to store your bitcoin keys. No Software updates needed, it's 100% offline, it leaves no traces on the blockchain. You can give it away as a gift or inheritance. You can send bitcoin to it and all you have to do is, to store it in a safe place. 

If you had something different in mind, please feel free to tell me.
Thanks, Anita

**Comment by 6102bitcoin** [comment]
I can't support a product that knowingly misleads users. If you can't use a hardware wallet use an offline device. If you can't use that use an online device. At no point trust someone else with your keys.

**Comment by 6102bitcoin** [comment]
Closing - presumably this is still the case.
