### ISSUE TITLE
Feedback Wanted | Proposed Hardware Wallet Listing Criteria

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#2]
Should the listing criteria for bitcoin-only hardware wallets be:

A) Products which **ONLY** maintain bitcoin-only firmware

B) Products which have an **OPTION** of installing bitcoin-only firmware **without being exposed to shitcoinery** (though the hardware wallet devs continue to maintain shitcoin firmware).

_Note: Hardware wallets releasing bitcoin-only firmware / product versions would only be listed if the bitcoin-only firmware / bitcoin-only product can be linked to without exposing those following the link to shitcoin promotion or promotion of shitcoin-supporting products. This includes the purchase of the product, the download and installation of the bitcoin-only firmware and the physical packaging._

C) List both [A] & [B] under different sub-headings like has been done for Custodial Wallets on the [wallets page](https://bitcoin-only.com/#wallets)

**More Info**

[Twitter Poll](https://twitter.com/6102bitcoin/status/1170699529341014016) indicates that both options have some support.

-----------------------------------

**Proposed Hardware Wallet Listing Eligibility:**

**ColdCard** - Eligible for listing (upon removal of legacy code) in both scenarios
- Dropped litecoin support in firmware version 2.1.3 ([Source](https://github.com/Coldcard/firmware/releases/tag/2019-09-06T1520-v2.1.3))
- Removed litecoin support from FAQ on website on 2019-09-08.
*Other comments:*
-  Legacy (inaccessible) litecoin code in chains.py will be removed in future firmware release. Though this code is inaccessible to the user it is planned to be removed in the next firmware update (2.1.4) thus listing can await that release to set a good precedent.

**Trezor** - Ineligible for listing under [A] assuming they continue shitcoin firmware support, Potentially elligible for listing under [B] if they have a standalone page to sell & download bitcoin only firmware.
- Bitcoin-Only firmware not yet available (but forthcoming) - Releasing bitcoin-only firmware on 2019/09/09 ([Source](https://twitter.com/pavolrusnak/status/1170660747967389697?s=12))

**BitBox02 - Bitcoin-Only edition**  - Unclear. Potentially eligible for listing under both scenarios (provided store page is changed) if bitcoin-only edition cannot accept shitcoin firmware (as has been claimed).
- Pre-sale of bitcoin-only version of their BitBox02 is ongoing ([Source](https://shop.shiftcrypto.ch/en/products/bitbox02-bitcoin-only-edition-5/))
- ~~The store page currently promotes altcoins by mentioning their other version of the product which 'supports Litecoin, Ethereum, ERC-20 tokens~~ *' (FIXED)

*Note: These (and all other 'altcoins' aka shtcoins) are not worth wasting your time or money on. Stick to [bitcoin-only](https://bitcoin-only.com). *

**Comment by 6102bitcoin** [comment]
Another option [C] is to list both [A] & [B] under different sub-headings like has been done for Custodial Wallets on the [wallets page](https://bitcoin-only.com/#wallets)

**Comment by psychedelicbart** [comment]
I'm going with A because this website and Bitcoiners (in general) have high standards when it comes to choosing which businesses to support. Listing products that are Bitcoin-only gives more recognition/prestige to companies like Coinkite & Casa. If we choose B or C, we're sending a message to shitcoin companies saying it's ok to support shitcoins as long as there's a Bitcoin-only version.

**Comment by Stadicus** [comment]
Preamble: I might be a bit biased, working at Shift. But this is my personal feedback as a (non-toxic) Bitcoin minimalist, and user of Bitcoin-only services whenever possible. 

For me A) and B) are two very different things. Not sure if everybody reads it this way, but this caputres the essence for me.

A) is ideology-driven, meaning to support Bitcoin-only companies, regardless of what product or service they provide. It's dogmatic in the way that functionally better products, even if they benefit Bitcoin Maximalists and being guaranteed to be Bitcoin-only, are excluded because the manufacturer is not "pure" enough.

B) focuses on the outcome. A Bitcoin-only product is listed if it is a good Bitcoin-only product, not judging "ideological pureness" of the producer (as long as it's honest and not fraudulent/scammy). Many cite that resources are wasted on altcoin support. I think it could very well be the other way round, revenues from altcoin-versions paying for an overall better product. Hardware has huge initial costs if the goal is to produce at scale and for a mass market. I like the Coldcard, have several, but that's a very nice product and not what I would recommend to my parents.

I see a third criteria: is the hardware sold as Bitcoin-only and is this choice locked in for life (like Coldcard or BitBox), or can a different altcoin firmware just be flashed onto the "Bitcoin-only" version?

For me personally, I care mostly about buying a quality Bitcoin-only product with the best security assurances (in this context: no unnecessary lines of code for altcoins). Just my 5 satoshis.

**Comment by 6102bitcoin** [comment]
Thanks both - some interesting ideas.

I'm currently leaning towards [C] because I prioritize putting quality bitcoin-only tools in peoples hands over supporting bitcoin-only businesses (though I do want to do this where possible because in the long run supporting bitcoin-only businesses is an effective way to put quality bitcoin-only tools in peoples hands). 

I want to reiterate that with [B] users will not be exposed to shitcoinery: _Hardware wallets releasing bitcoin-only firmware / product versions would only be listed if the bitcoin-only firmware / bitcoin-only product **can be linked to without exposing those following the link to shitcoin promotion or promotion of shitcoin-supporting products**. This includes the purchase of the product, the download and installation of the bitcoin-only firmware and the physical packaging._

I expect BitBox & other smaller hardware wallet manufacturers to sufficiently adaptive to meet this requirement. For example, BitBox have already removed the comment I had issue with from their BitBox02 Bitcoin-Only edition store page. In contrast, my expectation is that the other two large hardware wallet manufacturers will struggle to deliver a bitcoin-only experience, and will thus not be listed. I hope I'm proved wrong.

I agree with @psychedelicbart that recognition & prestige are nice byproducts, I think that this can be continued by clearly highlighting when hardware is exclusively bitcoin-only. There could even be a note suggesting that people consider supporting HW companies which are exclusively bitcoin-only because the money they spend directly contributes to new bitcoin features (as opposed to 1000 new shitcoins being added to the wallet).

There is clearly lots to think about on this issue so I won't rush into anything to give people time to express their thoughts.

**Comment by 6102bitcoin** [comment]
Luke Childs [posted](https://twitter.com/lukechilds/status/1171034687306981376?s=19) an interesting analysis of the Ledger firmware and showed that "The code base is littered with if statements branching off logic depending on the coin type." 

I'm going to go with [A] to encourage people to support ONLY bitcoin-only projects for now. 

Supporting companies building only bitcoin-only devices is a sure way to accelerate the development of future bitcoin-only hardware and firmware updates. 

If/when projects that would be acceptable under [B] become available I'm happy to revisit this decision, but currently there are no projects that meet [B] and are widely recognised as secure.

Multi-device multisig is important to some users and thus this would be a factor in reconsidering adding products which meet [B].

**Comment by KISBITCOIN** [comment]
I like [C] the best. Listing them separately creates an opportunity to  explain why [A] is the best choice. Ever chance to educate should be capitalized.

**Comment by elvissio** [comment]
As to **BitBox02 - Bitcoin only edition** we'd like to clear the claim why it cannot accept shitcoin/alternative firmware:

The device will only run firmware signed by Shift. This is verified when the device is plugged in.

We have different keys for the editions, so firmware signed by one set of keys will not be able to run on a device containing the other set of keys.

**Comment by 6102bitcoin** [comment]
Requirement Set - [LINK](https://github.com/bitcoin-only/bitcoin-only/issues/78)

Locking this conversation - Please feel free to share thoughts on the linked requirement issue.
