### ISSUE TITLE
Feature Suggestion: Add Youtube shows to Podcasts

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#298]
There are some good regularly-released youtube shows that would be good additions to the site. The Videos section currently lists more one-off of tutorial videos.

Suggest renaming the Podcasts sections to Podcasts/Shows or leave name as-is and start adding shows there.

Examples:
Simply Bitcoin - https://www.youtube.com/channel/UCB6Q0S1gUHXMe5-Jjx0_laQ/videos
Satoshi en Venezuela - https://www.youtube.com/c/SatoshienVenezuela/videos

**Comment by 6102bitcoin** [comment]
Good thinking - Do you think we should just have a Youtube section?

**Comment by pardus79** [comment]
Depends on if there are enough shows to warrant a page.

I think consolidating podcasts & shows is ok though, since they are pretty much the same content except split between audio & video. There is some overlap too since there are some shows that later release audio of shows as podcasts.

I'm also fine with just adding them as "Video Podcasts" on the podcast page to keep things simple.

**Comment by 6102bitcoin** [comment]
"Video Podcasts" Sounds good - I'll add it now

**Comment by 6102bitcoin** [comment]
On reflection - Maybe we should just add them as "Video Podcasts" on this page https://bitcoin-only.com/#videos

**Comment by pardus79** [comment]
The only reason why I don't think they should go to Videos is that at this point, the videos section only has tutorials and misc one-off videos, not ongoing shows.

I see the podcasts section to be more "recent news & interviews" which video podcasts would go with. 

In this case, I would say grouping them by content rather than by the delivery medium would be more helpful for people looking for this kind of information.

**Comment by 6102bitcoin** [comment]
Although I do see your reasoning I think it gets complicated having video shows on the podcasts page because of the language issue. 

If it was like this:

Podcasts
- English
- Language 2
- Language 3

Video Podcasts
- English
- Language 2
- Language 3

English speakers might not scroll down to see the video podcasts section because the rest of the screen appears to be other languages.

If instead we did this:

English 
- Podcasts
- Video Podcasts

Language 2
- Podcasts
- Video Podcasts

Language 3
- Podcasts
- Video Podcasts

It becomes very cluttered.

It is also somewhat arbitrary whether a video channel is a podcast or a regular show. Some of the podcasts listed are not made very frequently, and some non-podcast shows are very regular.

For now, lets try adding the video podcasts to the video section (at the top) and adding a link to that section on the podcasts page.

**Comment by pardus79** [comment]
> For now, lets try adding the video podcasts to the video section (at the top) and adding a link to that section on the podcasts page.

ACK

Solid solution

**Comment by 6102bitcoin** [comment]
Done! 
- [Add Video Podcasts Section](https://github.com/bitcoin-only/bitcoin-only/commit/48c2963a7e630abf76476f797b039437cabefc47)
- [Add Button](https://github.com/bitcoin-only/bitcoin-only/commit/7ecca0fa19365e1a589b39725d7d91b2b345528b)
