### ISSUE TITLE
Feedback Wanted | Small Store Listing

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#31]
Some very niche small stores which are bitcoin only have requested to be added.
I think these are most suitable for the spend bitcoin page however they are so niche that the general audience of bitcoin-only may not find them useful (lowering signal:noise)

I propose that either there is a niche stores page or we don't list this type of store.

Interested to hear thoughts from users and contributers.

**Comment by joe-rodgers** [comment]
Do these stores only accept Bitcoin as a payments method? Are they related to Bitcoin besides payment method?

If they are only being considered to be added to Bitcoin-only because they only accept Bitcoin for payment, I don't think it makes sense, seems like they should be a Bitcoin related business to be added. 

That being said, I can see the value in having a list of stores that accept Bitcoin for payments. I assume the list will eventually be too large to manage, and at that point the list won't matter anymore. 

If you have cycles, I'd suggest making a Bitcoin only payments page.

**Comment by dstrukt** [comment]
Second joe's thoughts. 

It'd definitely be nice to see a list of stores that accept bitcoin (only) for payments, and I have seen a few loose compilations floating around the internets, but the maintenance of that would likely be a nightmare.

**Comment by 6102bitcoin** [comment]
Agreed - If a store is bitcoin-only AND sells bitcoin related products/services they will be listed.

There are far too many websites that simply accept bitcoin but don't sell bitcoin related products/services - It would be impossible to keep track.
