### ISSUE TITLE
Content Suggestion: Strike as a Custodial Accounts

### ISSUE THREAD

**Issue by dmp1ce** [bitcoin-only/bitcoin-only#405]
1) Link to Content: https://beta.strike.me/
2) Briefly Describe Content: Strike is already under "Get Bitcoin" but I was looking for it under Lightning wallets.
3) Suggested Section: Custodial Accounts

**Comment by pardus79** [comment]
Strike is not a lightning wallet. It stores fiat for users and uses lightning as a payment rail. No user bitcoin is stored.

**Comment by dmp1ce** [comment]
I guess I don't understand. I thought Strike could pay a lightning invoice just like other lightning wallets.

**Comment by pardus79** [comment]
Working with fiat doesn't mean it's not bitcoin only. Else every exchange would have to be de-listed.

So yes, while Strike lets you pay lightning invoices like a wallet, it is not storing any bitcoin on behalf of it's users so it's not really a bitcoin wallet. But I see your point since users can use Strike like a bitcoin wallet, to send bitcoin. But since it doesn't store any bitcoin, I think it would add confusion if it was listed under the wallet section.

**Comment by 6102bitcoin** [comment]
I agree with Pardus on this.
