### ISSUE TITLE
Content Suggestion: lnart.co

### ISSUE THREAD

**Issue by lnartco** [bitcoin-only/bitcoin-only#429]
1) Link to Content: https://lnart.co/
2) Briefly Describe Content: Lightning Network-only Art Prints
3) Suggested Section: SPEND BITCOIN

**Comment by 6102bitcoin** [comment]
Thanks for raising the issue. Looking at the site although it is bitcoin-only is isn't a bitcoin store (the products aren't bitcoin related). We have not been listing stores of this type because I imagine there will be an overwhelming number and it will be hard to keep track. If this changes I will add this store (adding a niche-store tag).
