### ISSUE TITLE
Content Suggestion: HARDBLOCK BITCOIN EXCHANGE

### ISSUE THREAD

**Issue by JeremyMajid** [bitcoin-only/bitcoin-only#463]
1) Link to Content: WWW.HARDBLOCK.COM.AU
2) Briefly Describe Content: AUSTRALIAN BASED BITCOIN EXCHANGE ESTABLISHED 2014. 
3) Suggested Section: GET BITCOIN > BUY (OTHER) - WE ARE REGULATED BY AUSTRAC AND DO KYC

**Comment by Daunus** [comment]
Hi,

 We are a Bitcoin only exchange operating in Australia since 2014. We are listed on bitcoin.org and it would be great if we could get listed here also. https://bitcoin.org/en/exchanges#australia

I am the founder and this is my personal twitter https://twitter.com/danWilcz. Please reach out if you have any questions.

Thanks for your help https://twitter.com/danWilcz

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/e7811f3ca6c99a8d8a0efc07f90a80ba34af1693)
